[[main]]
  identifier = "home"
  pre = ""
  post = ""
  name = "首页"
  url = "/"
  title = ""
  weight = 1
[[main]]
  identifier = "news"
  pre = ""
  post = ""
  name = "资讯"
  url = "/news/"
  title = ""
  weight = 2
[[main]]
  identifier = "navigation"
  pre = ""
  post = ""
  name = "导航"
  url = "/navigation/"
  title = ""
  weight = 3
[[main]]
  identifier = "games"
  pre = ""
  post = ""
  name = "玩游戏挣钱"
  url = "/games/"
  title = ""
  weight = 4
[[main]]
  identifier = "community"
  pre = ""
  post = ""
  name = "社区"
  url = "/community/"
  title = ""
  weight = 5
